// swift-tools-version:5.3
// Autogenerated by Localiser (https://github.com/gotev/localiser)
// DO NOT EDIT

import PackageDescription

let package = Package(
    name: "{{ projectPackageName }}",
    defaultLocalization: "Base",
    products: [
        .library(name: "{{ projectPackageName }}", targets: ["{{ projectPackageName }}"]),
    ],
    targets: [
        .target(name: "{{ projectPackageName }}", path: "Sources"),
    ]
)
