// Autogenerated by Localiser (https://github.com/gotev/localiser)
// DO NOT EDIT
import Foundation

extension String.{{ projectShortIdentifier|capitalize }} {
    public struct {{ projectNamespace }} {
    {% for translationFunction in translationFunctions %}

        {% if translationFunction['localisedKeyComment'] is not none %}
        {% for commentLine in translationFunction['localisedKeyComment'] %}
        {{ commentLine }}
        {% endfor %}
        {% endif %}
        public static func {{ translationFunction['name'] }}({{ translationFunction['parameters'] }}) -> {% if translationFunction['localisedKeyValueContainsHTML'] %}HTMLString{% else %}String{% endif %} {
            NSLocalizedString("{{ translationFunction['localisedKey'] }}",
                              tableName: "{{ projectNamespace }}",
                              bundle: Bundle.module,
                              comment: "{{ translationFunction['localisedKeyValue'] }}")
                {% for placeholder in translationFunction['placeholders'] %}
                .replacingOccurrences(of: "{{ placeholder['placeholder'] }}", with: "\({{ placeholder['variableName'] }})")
                {% endfor %}
                {% if translationFunction['localisedKeyValueContainsHTML'] %}
                .asHTMLString
                {% endif %}
        }
    {% endfor %}
    }

    public static var {{ projectNamespace|lower }}: {{ projectNamespace }}.Type { {{ projectNamespace }}.self }
}
