// Autogenerated by Localiser (https://github.com/gotev/localiser)
// DO NOT EDIT
import Foundation

extension String {
    public static var {{ projectShortIdentifier }}: {{ projectShortIdentifier|capitalize }}.Type {
        {{ projectShortIdentifier|capitalize }}.self
    }

    public struct {{ projectShortIdentifier|capitalize }} {}
}
