// Autogenerated by Localiser (https://github.com/gotev/localiser)
// DO NOT EDIT
import Foundation

public extension String {
    static var {{ projectShortIdentifier }}: {{ projectShortIdentifier|capitalize }}.Type {
        return {{ projectShortIdentifier|capitalize }}.self
    }

    struct {{ projectShortIdentifier|capitalize }} {}
    private class {{ projectShortIdentifier|capitalize }}Strings {}
    static let {{ projectShortIdentifier }}StringsBundle = Bundle(for: {{ projectShortIdentifier|capitalize }}Strings.self)
}