# Generated by Django 2.2.2 on 2019-06-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localisedkey',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
