# Generated by Django 2.2.2 on 2019-06-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_localisedkey_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedkey',
            name='temporary',
            field=models.BooleanField(default=False),
        ),
    ]
