# Generated by Django 2.2.2 on 2019-06-19 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_translatedkey_temporary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locale',
            name='slug',
            field=models.CharField(help_text='<a href="https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes" target="_blank">ISO 639-1</a> or <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2" target="_blank">ISO 3166-1</a> string. (e.g. it, en, fr, it-IT, en-US, ..)', max_length=5),
        ),
        migrations.AlterField(
            model_name='localisedkey',
            name='comment',
            field=models.TextField(blank=True, help_text='Something useful to specify what this key is for and where to use it (e.g. This is the text shown to the user only the first time he enters the app. You have to use it only in welcome screen.)', null=True),
        ),
        migrations.AlterField(
            model_name='namespace',
            name='name',
            field=models.CharField(help_text="The namespace is a way to group your strings. It's up to you to decide if you want to group them by feature, section or whatever else (e.g. home)", max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='default_language',
            field=models.ForeignKey(help_text='The base localisation of your project (e.g. en)', on_delete=django.db.models.deletion.CASCADE, to='database.Locale'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ios_deployment_target',
            field=models.CharField(help_text='The minimum iOS version you want to support (e.g. 11.4). Android minimum is set to API 18 (Android 4.3)', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='The name of your app (e.g. My App)', max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.CharField(help_text='The name of the organization which owns this project (e.g. ACME Org)', max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='package',
            field=models.CharField(help_text='The package (or bundle identifier) which will be used in the auto-generated strings library (e.g. com.company.project.strings)', max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_identifier',
            field=models.CharField(help_text='The identifier which will be used in the auto-generated libraries as the root to get access to your localisation strings from code. (e.g. iOS: Strings.shortidentifier.namespace.string(), Android: ShortidentifierStrings.namespace.string(context) )', max_length=10),
        ),
        migrations.AlterField(
            model_name='translatedkey',
            name='temporary',
            field=models.BooleanField(default=False, help_text='To speed up development and have the possibility to better define a translation later, you can mark a translated key as "Temporary" and change its value later. There\'s a filter which helps you see only temporary strings'),
        ),
    ]
