# Generated by Django 2.2.2 on 2019-06-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20190619_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='android_min_sdk',
            field=models.IntegerField(default=18, help_text='Minimum Android SDK version to support (e.g. 18 - Android 4.3)'),
        ),
        migrations.AddField(
            model_name='project',
            name='internal_maven_repo_url',
            field=models.CharField(blank=True, help_text='(optional) Internal maven repository URL to deploy the library locally on a dev computer. You can use $username placeholder. (e.g. file:///Users/$username/workspace/maven-repo/releases)', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='nexus_maven_repo_url',
            field=models.CharField(blank=True, help_text='(optional) Nexus (or Artifactory or other maven repo) maven repository URL. (e.g. https://maven.yourcompany.com/repository/your-library/)', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ios_deployment_target',
            field=models.CharField(default='11.4', help_text='The minimum iOS version you want to support (e.g. 11.4). Android minimum is set to API 18 (Android 4.3)', max_length=10),
        ),
    ]
