# Generated by Django 2.2.2 on 2019-08-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20190629_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='localisedkey',
            name='contains_HTML',
            field=models.BooleanField(default=False, help_text='Indicates if this localisation key contains HTML in its values'),
        ),
    ]
