# Generated by Django 2.2.2 on 2019-08-29 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0007_localisedkey_contains_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTranslatedKey',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('temporary', models.BooleanField(default=False, help_text='To speed up development and have the possibility to better define a translation later, you can mark a translated key as "Temporary" and change its value later. There\'s a filter which helps you see only temporary strings')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('localised_key', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.LocalisedKey')),
                ('slug', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.Locale')),
            ],
            options={
                'verbose_name': 'historical translated key',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of your app (e.g. My App)', max_length=128)),
                ('organization', models.CharField(help_text='The name of the organization which owns this project (e.g. ACME Org)', max_length=128)),
                ('package', models.CharField(help_text='The package (or bundle identifier) which will be used in the auto-generated strings library (e.g. com.company.project.strings)', max_length=128)),
                ('short_identifier', models.CharField(help_text='The identifier which will be used in the auto-generated libraries as the root to get access to your localisation strings from code. (e.g. iOS: Strings.shortidentifier.namespace.string(), Android: ShortidentifierStrings.namespace.string(context) )', max_length=10)),
                ('ios_deployment_target', models.CharField(default='11.4', help_text='The minimum iOS version you want to support (e.g. 11.4). Android minimum is set to API 18 (Android 4.3)', max_length=10)),
                ('android_min_sdk', models.IntegerField(default=18, help_text='Minimum Android SDK version to support (e.g. 18 - Android 4.3)')),
                ('internal_maven_repo_url', models.CharField(blank=True, help_text='(optional) Internal maven repository URL to deploy the library locally on a dev computer. file:///Users/yourusername/workspace/maven-repo/releases)', max_length=1024, null=True)),
                ('nexus_maven_repo_url', models.CharField(blank=True, help_text='(optional) Nexus (or Artifactory or other maven repo) maven repository URL. (e.g. https://maven.yourcompany.com/repository/your-library/)', max_length=1024, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('default_language', models.ForeignKey(blank=True, db_constraint=False, help_text='The base localisation of your project (e.g. en)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.Locale')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical project',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNamespace',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text="The namespace is a way to group your strings. It's up to you to decide if you want to group them by feature, section or whatever else (e.g. home)", max_length=128)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.Project')),
            ],
            options={
                'verbose_name': 'historical namespace',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLocalisedKey',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('comment', models.TextField(blank=True, help_text='Something useful to specify what this key is for and where to use it (e.g. This is the text shown to the user only the first time he enters the app. You have to use it only in welcome screen.)', null=True)),
                ('contains_HTML', models.BooleanField(default=False, help_text='Indicates if this localisation key contains HTML in its values')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('namespace', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.Namespace')),
            ],
            options={
                'verbose_name': 'historical localised key',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLocale',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('slug', models.CharField(help_text='<a href="https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes" target="_blank">ISO 639-1</a> or <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2" target="_blank">ISO 3166-1</a> string. (e.g. it, en, fr, it-IT, en-US, ..)', max_length=5)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical locale',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
