# Generated by Django 4.1.3 on 2022-11-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_historicallocale_historicallocalisedkey_historicalnamespace_historicalproject_historicaltranslatedke'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicallocale',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical locale', 'verbose_name_plural': 'historical locales'},
        ),
        migrations.AlterModelOptions(
            name='historicallocalisedkey',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical localised key', 'verbose_name_plural': 'historical localised keys'},
        ),
        migrations.AlterModelOptions(
            name='historicalnamespace',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical namespace', 'verbose_name_plural': 'historical namespaces'},
        ),
        migrations.AlterModelOptions(
            name='historicalproject',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical project', 'verbose_name_plural': 'historical projects'},
        ),
        migrations.AlterModelOptions(
            name='historicaltranslatedkey',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical translated key', 'verbose_name_plural': 'historical translated keys'},
        ),
        migrations.AlterField(
            model_name='historicallocale',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicallocalisedkey',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalnamespace',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltranslatedkey',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
