name: TestAppStringsSDK
options:
  bundleIdPrefix: com.my.org
  developmentLanguage: "it"
  deploymentTarget:
    iOS: "11.4"
targets:
  TestAppStrings:
    templates:
      - StringsFramework
targetTemplates:
  StringsFramework:
    platform: iOS
    type: framework
    info:
      path: ${target_name}.plist
      properties:
        CFBundleIdentifier: com.my.org
        CFBundleShortVersionString: "1.0"
    scheme: {}
    sources:
      - .